"""Research plan models."""

from typing import Literal

from pydantic import BaseModel, Field


class QueryAnalysis(BaseModel):
    """Query analysis results from Planning Agent."""

    keywords: list[str] = Field(default_factory=list, description="All extracted keywords")
    must_have_keywords: list[str] = Field(
        default_factory=list, description="Critical keywords that must appear in results"
    )
    entity_type: str = Field(default="unknown", description="Entity type: venture_capital, bank, etc.")
    jurisdiction: str | None = Field(None, description="Regulatory jurisdiction: 金管會, 中央銀行, etc.")
    time_period: str | None = Field(None, description="Time period if specified")
    query_type: str = Field(
        default="enforcement_search",
        description="Type of query: enforcement_search, court_judgment, legal_interpretation",
    )
    complexity: Literal["simple", "medium", "complex"] = Field(
        default="medium", description="Query complexity level"
    )


class PlanTask(BaseModel):
    """Individual task in research plan."""

    id: int = Field(..., description="Task ID")
    task: str = Field(..., description="Task description in Chinese")
    status: Literal["pending", "in_progress", "completed", "failed"] = Field(
        default="pending", description="Task status"
    )
    search_method: Literal["vector_search", "hard_search", "hybrid"] = Field(
        default="vector_search", description="Search method to use"
    )
    estimated_time: int | None = Field(None, description="Estimated time in seconds")


class ResearchPlan(BaseModel):
    """Complete research plan generated by Planning Agent."""

    analysis: QueryAnalysis = Field(..., description="Query analysis results")
    tasks: list[PlanTask] = Field(..., description="List of research tasks")
    max_results: int = Field(default=5, description="Maximum results to retrieve")
    use_hard_search: bool = Field(default=False, description="Whether to use hard search (grep)")
    estimated_total_time: int = Field(default=0, description="Estimated total time in seconds")

    class Config:
        json_schema_extra = {
            "example": {
                "analysis": {
                    "keywords": ["創投", "裁罰", "金管會"],
                    "must_have_keywords": ["創投", "創業投資"],
                    "entity_type": "venture_capital",
                    "jurisdiction": "證券期貨局",
                    "time_period": None,
                    "query_type": "enforcement_search",
                    "complexity": "complex",
                },
                "tasks": [
                    {
                        "id": 1,
                        "task": "向量搜索：創投, 裁罰",
                        "status": "pending",
                        "search_method": "vector_search",
                        "estimated_time": 10,
                    },
                    {
                        "id": 2,
                        "task": "深度搜索：grep 關鍵字 ['創投', '創業投資']",
                        "status": "pending",
                        "search_method": "hard_search",
                        "estimated_time": 30,
                    },
                ],
                "max_results": 10,
                "use_hard_search": True,
                "estimated_total_time": 60,
            }
        }
