"""initial_schema

Revision ID: b8b4f491f6c7
Revises:
Create Date: 2025-12-01 16:48:08.795709

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b8b4f491f6c7'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('concept_type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_concept_type'), 'concepts', ['concept_type'], unique=False)
    op.create_index(op.f('ix_concepts_name'), 'concepts', ['name'], unique=True)
    op.create_table('document_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id_1', sa.Text(), nullable=False),
    sa.Column('doc_id_2', sa.Text(), nullable=False),
    sa.Column('relationship_type', sa.Text(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("relationship_type IN ('related', 'supersedes', 'amendment', 'references', 'similar')", name='ck_relationship_type'),
    sa.CheckConstraint('strength >= 0 AND strength <= 1', name='ck_relationship_strength'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id_1', 'doc_id_2', 'relationship_type', name='uq_doc_rel')
    )
    op.create_index(op.f('ix_document_relationships_doc_id_1'), 'document_relationships', ['doc_id_1'], unique=False)
    op.create_index(op.f('ix_document_relationships_doc_id_2'), 'document_relationships', ['doc_id_2'], unique=False)
    op.create_index(op.f('ix_document_relationships_relationship_type'), 'document_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_document_relationships_strength'), 'document_relationships', ['strength'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_created_at'), 'history', ['created_at'], unique=False)
    op.create_index(op.f('ix_history_session_id'), 'history', ['session_id'], unique=False)
    op.create_table('model_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('config_type', sa.Text(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configs_config_type'), 'model_configs', ['config_type'], unique=False)
    op.create_index(op.f('ix_model_configs_is_active'), 'model_configs', ['is_active'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_category'), 'settings', ['category'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('wiki_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category_type', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("category_type IN ('authority', 'institution', 'violation', 'document_type')", name='ck_wiki_category_type'),
    sa.ForeignKeyConstraint(['parent_id'], ['wiki_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'category_type', name='uq_wiki_category_name_type')
    )
    op.create_index(op.f('ix_wiki_categories_category_type'), 'wiki_categories', ['category_type'], unique=False)
    op.create_index(op.f('ix_wiki_categories_document_count'), 'wiki_categories', ['document_count'], unique=False)
    op.create_index(op.f('ix_wiki_categories_parent_id'), 'wiki_categories', ['parent_id'], unique=False)
    op.create_table('wiki_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_type', sa.Text(), nullable=False),
    sa.Column('stat_key', sa.Text(), nullable=True),
    sa.Column('stat_value', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wiki_statistics_calculated_at'), 'wiki_statistics', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_wiki_statistics_stat_key'), 'wiki_statistics', ['stat_key'], unique=False)
    op.create_index(op.f('ix_wiki_statistics_stat_type'), 'wiki_statistics', ['stat_type'], unique=False)
    op.create_table('document_concepts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.Text(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'concept_id', name='uq_doc_concept')
    )
    op.create_index(op.f('ix_document_concepts_concept_id'), 'document_concepts', ['concept_id'], unique=False)
    op.create_index(op.f('ix_document_concepts_doc_id'), 'document_concepts', ['doc_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('document_date', sa.Text(), nullable=True),
    sa.Column('issuing_authority', sa.Text(), nullable=True),
    sa.Column('related_institutions', sa.Text(), nullable=True),
    sa.Column('penalty_amount', sa.Text(), nullable=True),
    sa.Column('violation_types', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.Text(), nullable=True),
    sa.Column('indexed', sa.Boolean(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('metadata_extracted', sa.Boolean(), nullable=True),
    sa.Column('metadata_extraction_status', sa.Text(), nullable=True),
    sa.Column('metadata_extraction_error', sa.Text(), nullable=True),
    sa.Column('metadata_extraction_attempts', sa.Integer(), nullable=True),
    sa.Column('metadata_last_extracted_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_edited_by_user', sa.Boolean(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('pipeline_stage', sa.Text(), nullable=True),
    sa.Column('pipeline_status', sa.Text(), nullable=True),
    sa.Column('pipeline_data', sa.Text(), nullable=True),
    sa.Column('pipeline_started_at', sa.DateTime(), nullable=True),
    sa.Column('pipeline_completed_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.Text(), nullable=True),
    sa.Column('case_number', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('document_status', sa.Text(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['wiki_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_doc_id'), 'documents', ['doc_id'], unique=True)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_filename'), 'documents', ['filename'], unique=False)
    op.create_index(op.f('ix_documents_indexed'), 'documents', ['indexed'], unique=False)
    op.create_index(op.f('ix_documents_issuing_authority'), 'documents', ['issuing_authority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_issuing_authority'), table_name='documents')
    op.drop_index(op.f('ix_documents_indexed'), table_name='documents')
    op.drop_index(op.f('ix_documents_filename'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_document_concepts_doc_id'), table_name='document_concepts')
    op.drop_index(op.f('ix_document_concepts_concept_id'), table_name='document_concepts')
    op.drop_table('document_concepts')
    op.drop_index(op.f('ix_wiki_statistics_stat_type'), table_name='wiki_statistics')
    op.drop_index(op.f('ix_wiki_statistics_stat_key'), table_name='wiki_statistics')
    op.drop_index(op.f('ix_wiki_statistics_calculated_at'), table_name='wiki_statistics')
    op.drop_table('wiki_statistics')
    op.drop_index(op.f('ix_wiki_categories_parent_id'), table_name='wiki_categories')
    op.drop_index(op.f('ix_wiki_categories_document_count'), table_name='wiki_categories')
    op.drop_index(op.f('ix_wiki_categories_category_type'), table_name='wiki_categories')
    op.drop_table('wiki_categories')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_category'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_model_configs_is_active'), table_name='model_configs')
    op.drop_index(op.f('ix_model_configs_config_type'), table_name='model_configs')
    op.drop_table('model_configs')
    op.drop_index(op.f('ix_history_session_id'), table_name='history')
    op.drop_index(op.f('ix_history_created_at'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_document_relationships_strength'), table_name='document_relationships')
    op.drop_index(op.f('ix_document_relationships_relationship_type'), table_name='document_relationships')
    op.drop_index(op.f('ix_document_relationships_doc_id_2'), table_name='document_relationships')
    op.drop_index(op.f('ix_document_relationships_doc_id_1'), table_name='document_relationships')
    op.drop_table('document_relationships')
    op.drop_index(op.f('ix_concepts_name'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_concept_type'), table_name='concepts')
    op.drop_table('concepts')
    # ### end Alembic commands ###
