"""Add full_content column to documents

Revision ID: ec28f35794a8
Revises: 18bdd6784d19
Create Date: 2025-11-19 14:41:48.142584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec28f35794a8'
down_revision: Union[str, Sequence[str], None] = '18bdd6784d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('name', sa.Text(), nullable=False))
    op.alter_column('concepts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('concepts', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('concepts', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_concepts_count'), table_name='concepts')
    op.drop_index(op.f('idx_concepts_name'), table_name='concepts')
    op.drop_index(op.f('idx_concepts_type'), table_name='concepts')
    op.create_index(op.f('ix_concepts_concept_type'), 'concepts', ['concept_type'], unique=False)
    op.create_index(op.f('ix_concepts_name'), 'concepts', ['name'], unique=True)
    op.drop_column('concepts', 'concept_name')
    op.drop_column('concepts', 'keywords')
    op.drop_column('concepts', 'metadata')
    op.drop_column('concepts', 'document_count')
    op.add_column('document_concepts', sa.Column('confidence', sa.Float(), nullable=True))
    op.alter_column('document_concepts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('document_concepts', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_doc_concepts_concept_id'), table_name='document_concepts')
    op.drop_index(op.f('idx_doc_concepts_doc_id'), table_name='document_concepts')
    op.drop_index(op.f('idx_doc_concepts_relevance'), table_name='document_concepts')
    op.create_index(op.f('ix_document_concepts_concept_id'), 'document_concepts', ['concept_id'], unique=False)
    op.create_index(op.f('ix_document_concepts_doc_id'), 'document_concepts', ['doc_id'], unique=False)
    op.create_unique_constraint('uq_doc_concept', 'document_concepts', ['doc_id', 'concept_id'])
    op.drop_constraint(None, 'document_concepts', type_='foreignkey')
    op.create_foreign_key(None, 'document_concepts', 'concepts', ['concept_id'], ['id'])
    op.drop_column('document_concepts', 'relevance_score')
    op.alter_column('document_relationships', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('document_relationships', 'strength',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.5)'))
    op.alter_column('document_relationships', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_doc_rel_doc1'), table_name='document_relationships')
    op.drop_index(op.f('idx_doc_rel_doc2'), table_name='document_relationships')
    op.drop_index(op.f('idx_doc_rel_strength'), table_name='document_relationships')
    op.drop_index(op.f('idx_doc_rel_type'), table_name='document_relationships')
    op.create_index(op.f('ix_document_relationships_doc_id_1'), 'document_relationships', ['doc_id_1'], unique=False)
    op.create_index(op.f('ix_document_relationships_doc_id_2'), 'document_relationships', ['doc_id_2'], unique=False)
    op.create_index(op.f('ix_document_relationships_relationship_type'), 'document_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_document_relationships_strength'), 'document_relationships', ['strength'], unique=False)
    op.create_unique_constraint('uq_doc_rel', 'document_relationships', ['doc_id_1', 'doc_id_2', 'relationship_type'])
    op.add_column('documents', sa.Column('full_content', sa.Text(), nullable=True))
    op.alter_column('documents', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('documents', 'metadata_last_extracted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('documents', 'extraction_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('documents', 'pipeline_started_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('documents', 'pipeline_completed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('documents', 'last_accessed',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('documents', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_documents_case_number'), table_name='documents')
    op.drop_index(op.f('idx_documents_category'), table_name='documents')
    op.drop_index(op.f('idx_documents_created'), table_name='documents')
    op.drop_index(op.f('idx_documents_doc_id'), table_name='documents')
    op.drop_index(op.f('idx_documents_document_type'), table_name='documents')
    op.drop_index(op.f('idx_documents_filename'), table_name='documents')
    op.drop_index(op.f('idx_documents_indexed'), table_name='documents')
    op.drop_index(op.f('idx_documents_issuing_authority'), table_name='documents')
    op.drop_index(op.f('idx_documents_status'), table_name='documents')
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_doc_id'), 'documents', ['doc_id'], unique=True)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_filename'), 'documents', ['filename'], unique=False)
    op.create_index(op.f('ix_documents_indexed'), 'documents', ['indexed'], unique=False)
    op.create_index(op.f('ix_documents_issuing_authority'), 'documents', ['issuing_authority'], unique=False)
    op.create_foreign_key(None, 'documents', 'wiki_categories', ['category_id'], ['id'])
    op.drop_column('documents', 'file_size')
    op.alter_column('history', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('history', 'cost_usd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('history', 'processing_time_seconds',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('history', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_history_created'), table_name='history')
    op.drop_index(op.f('idx_history_model'), table_name='history')
    op.drop_index(op.f('idx_history_session'), table_name='history')
    op.create_index(op.f('ix_history_created_at'), 'history', ['created_at'], unique=False)
    op.create_index(op.f('ix_history_session_id'), 'history', ['session_id'], unique=False)
    op.drop_column('history', 'metadata')
    op.alter_column('model_configs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('model_configs', 'temperature',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('model_configs', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('model_configs', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_model_configs_active'), table_name='model_configs')
    op.drop_index(op.f('idx_model_configs_type'), table_name='model_configs')
    op.create_index(op.f('ix_model_configs_config_type'), 'model_configs', ['config_type'], unique=False)
    op.create_index(op.f('ix_model_configs_is_active'), 'model_configs', ['is_active'], unique=False)
    op.alter_column('settings', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('settings', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('settings', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_settings_category'), table_name='settings')
    op.drop_index(op.f('idx_settings_key'), table_name='settings')
    op.create_index(op.f('ix_settings_category'), 'settings', ['category'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.alter_column('wiki_categories', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('wiki_categories', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('wiki_categories', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_wiki_categories_count'), table_name='wiki_categories')
    op.drop_index(op.f('idx_wiki_categories_parent'), table_name='wiki_categories')
    op.drop_index(op.f('idx_wiki_categories_type'), table_name='wiki_categories')
    op.create_index(op.f('ix_wiki_categories_category_type'), 'wiki_categories', ['category_type'], unique=False)
    op.create_index(op.f('ix_wiki_categories_document_count'), 'wiki_categories', ['document_count'], unique=False)
    op.create_index(op.f('ix_wiki_categories_parent_id'), 'wiki_categories', ['parent_id'], unique=False)
    op.create_unique_constraint('uq_wiki_category_name_type', 'wiki_categories', ['name', 'category_type'])
    op.drop_constraint(None, 'wiki_categories', type_='foreignkey')
    op.create_foreign_key(None, 'wiki_categories', 'wiki_categories', ['parent_id'], ['id'])
    op.alter_column('wiki_statistics', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('wiki_statistics', 'calculated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_wiki_stats_calculated'), table_name='wiki_statistics')
    op.drop_index(op.f('idx_wiki_stats_key'), table_name='wiki_statistics')
    op.drop_index(op.f('idx_wiki_stats_type'), table_name='wiki_statistics')
    op.create_index(op.f('ix_wiki_statistics_calculated_at'), 'wiki_statistics', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_wiki_statistics_stat_key'), 'wiki_statistics', ['stat_key'], unique=False)
    op.create_index(op.f('ix_wiki_statistics_stat_type'), 'wiki_statistics', ['stat_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wiki_statistics_stat_type'), table_name='wiki_statistics')
    op.drop_index(op.f('ix_wiki_statistics_stat_key'), table_name='wiki_statistics')
    op.drop_index(op.f('ix_wiki_statistics_calculated_at'), table_name='wiki_statistics')
    op.create_index(op.f('idx_wiki_stats_type'), 'wiki_statistics', ['stat_type'], unique=False)
    op.create_index(op.f('idx_wiki_stats_key'), 'wiki_statistics', ['stat_key'], unique=False)
    op.create_index(op.f('idx_wiki_stats_calculated'), 'wiki_statistics', ['calculated_at'], unique=False)
    op.alter_column('wiki_statistics', 'calculated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('wiki_statistics', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'wiki_categories', type_='foreignkey')
    op.create_foreign_key(None, 'wiki_categories', 'wiki_categories', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_wiki_category_name_type', 'wiki_categories', type_='unique')
    op.drop_index(op.f('ix_wiki_categories_parent_id'), table_name='wiki_categories')
    op.drop_index(op.f('ix_wiki_categories_document_count'), table_name='wiki_categories')
    op.drop_index(op.f('ix_wiki_categories_category_type'), table_name='wiki_categories')
    op.create_index(op.f('idx_wiki_categories_type'), 'wiki_categories', ['category_type'], unique=False)
    op.create_index(op.f('idx_wiki_categories_parent'), 'wiki_categories', ['parent_id'], unique=False)
    op.create_index(op.f('idx_wiki_categories_count'), 'wiki_categories', ['document_count'], unique=False)
    op.alter_column('wiki_categories', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('wiki_categories', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('wiki_categories', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_category'), table_name='settings')
    op.create_index(op.f('idx_settings_key'), 'settings', ['key'], unique=False)
    op.create_index(op.f('idx_settings_category'), 'settings', ['category'], unique=False)
    op.alter_column('settings', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('settings', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('settings', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_model_configs_is_active'), table_name='model_configs')
    op.drop_index(op.f('ix_model_configs_config_type'), table_name='model_configs')
    op.create_index(op.f('idx_model_configs_type'), 'model_configs', ['config_type'], unique=False)
    op.create_index(op.f('idx_model_configs_active'), 'model_configs', ['is_active'], unique=False)
    op.alter_column('model_configs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('model_configs', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('model_configs', 'temperature',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('model_configs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('history', sa.Column('metadata', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_history_session_id'), table_name='history')
    op.drop_index(op.f('ix_history_created_at'), table_name='history')
    op.create_index(op.f('idx_history_session'), 'history', ['session_id'], unique=False)
    op.create_index(op.f('idx_history_model'), 'history', ['model_used'], unique=False)
    op.create_index(op.f('idx_history_created'), 'history', ['created_at'], unique=False)
    op.alter_column('history', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('history', 'processing_time_seconds',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('history', 'cost_usd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('history', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('documents', sa.Column('file_size', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_issuing_authority'), table_name='documents')
    op.drop_index(op.f('ix_documents_indexed'), table_name='documents')
    op.drop_index(op.f('ix_documents_filename'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.create_index(op.f('idx_documents_status'), 'documents', ['document_status'], unique=False)
    op.create_index(op.f('idx_documents_issuing_authority'), 'documents', ['issuing_authority'], unique=False)
    op.create_index(op.f('idx_documents_indexed'), 'documents', ['indexed'], unique=False)
    op.create_index(op.f('idx_documents_filename'), 'documents', ['filename'], unique=False)
    op.create_index(op.f('idx_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('idx_documents_doc_id'), 'documents', ['doc_id'], unique=False)
    op.create_index(op.f('idx_documents_created'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('idx_documents_category'), 'documents', ['category_id'], unique=False)
    op.create_index(op.f('idx_documents_case_number'), 'documents', ['case_number'], unique=False)
    op.alter_column('documents', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('documents', 'last_accessed',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('documents', 'pipeline_completed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('documents', 'pipeline_started_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('documents', 'extraction_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('documents', 'metadata_last_extracted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('documents', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('documents', 'full_content')
    op.drop_constraint('uq_doc_rel', 'document_relationships', type_='unique')
    op.drop_index(op.f('ix_document_relationships_strength'), table_name='document_relationships')
    op.drop_index(op.f('ix_document_relationships_relationship_type'), table_name='document_relationships')
    op.drop_index(op.f('ix_document_relationships_doc_id_2'), table_name='document_relationships')
    op.drop_index(op.f('ix_document_relationships_doc_id_1'), table_name='document_relationships')
    op.create_index(op.f('idx_doc_rel_type'), 'document_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('idx_doc_rel_strength'), 'document_relationships', ['strength'], unique=False)
    op.create_index(op.f('idx_doc_rel_doc2'), 'document_relationships', ['doc_id_2'], unique=False)
    op.create_index(op.f('idx_doc_rel_doc1'), 'document_relationships', ['doc_id_1'], unique=False)
    op.alter_column('document_relationships', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('document_relationships', 'strength',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.5)'))
    op.alter_column('document_relationships', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('document_concepts', sa.Column('relevance_score', sa.REAL(), server_default=sa.text('(1.0)'), nullable=True))
    op.drop_constraint(None, 'document_concepts', type_='foreignkey')
    op.create_foreign_key(None, 'document_concepts', 'concepts', ['concept_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_doc_concept', 'document_concepts', type_='unique')
    op.drop_index(op.f('ix_document_concepts_doc_id'), table_name='document_concepts')
    op.drop_index(op.f('ix_document_concepts_concept_id'), table_name='document_concepts')
    op.create_index(op.f('idx_doc_concepts_relevance'), 'document_concepts', ['relevance_score'], unique=False)
    op.create_index(op.f('idx_doc_concepts_doc_id'), 'document_concepts', ['doc_id'], unique=False)
    op.create_index(op.f('idx_doc_concepts_concept_id'), 'document_concepts', ['concept_id'], unique=False)
    op.alter_column('document_concepts', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('document_concepts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('document_concepts', 'confidence')
    op.add_column('concepts', sa.Column('document_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('concepts', sa.Column('metadata', sa.TEXT(), nullable=True))
    op.add_column('concepts', sa.Column('keywords', sa.TEXT(), nullable=True))
    op.add_column('concepts', sa.Column('concept_name', sa.TEXT(), nullable=False))
    op.drop_index(op.f('ix_concepts_name'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_concept_type'), table_name='concepts')
    op.create_index(op.f('idx_concepts_type'), 'concepts', ['concept_type'], unique=False)
    op.create_index(op.f('idx_concepts_name'), 'concepts', ['concept_name'], unique=False)
    op.create_index(op.f('idx_concepts_count'), 'concepts', ['document_count'], unique=False)
    op.alter_column('concepts', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('concepts', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('concepts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('concepts', 'name')
    # ### end Alembic commands ###
